dubbo :
  protocol : 
    port : -1
    name  : dubbo
  application : 
    name : hello-world-app-provider
  registry :
    address : zookeeper://localhost:2181
  packageName : com.ysh.dubbo.provide.service.impl
  admin :
    root :
      password : root
    guest :
      password : password

server :
  port : 8083




